### ISSUE TITLE
[feat] 스티커 모달 창 띄우기

### ISSUE THREAD

**Issue by minseok1015** [2022-Winter-Bootcamp-Team-K/frontend#41]
## ✨ 구현 할 기능
디자인은 나중에 같이 진행하고 일단 모달창을 띄워보겠습니다

## 📢 구현 방식
기능을 구현할 방식에 대해 설명해주세요.

<br>

### 📕 래퍼런스

**Comment by junvhui** [comment]
잘쓰겠습니다.
